info:
  id: ${name:application}
spring:
  application:
    name: ${info.id}
logging:
  level:
    com.netflix.discovery: 'OFF'
    org.springframework.security: DEBUG
cloudfoundry:
  sso:
    tokenUri: http://localhost:8080/uaa/oauth/token
    authorizationUri: http://localhost:8080/uaa/oauth/authorize
    clientId: app
    clientSecret: appclientsecret
